# coding: utf-8
# Python 3


# 2020-08-15 杨房沟 BIM 系统应用层用户信息列表
# 全部信息太大，为减小文件体积，只保留一个用户的信息
construction_user_list = [
    {
        "id": 369,
        "username": "wang_p",
        "email": "",
        "last_login": None,
        "account": {
            "person_id": "1259926678",
            "person_name": "汪鹏",
            "person_code": "PER368",
            "person_type": "C_PER",
            "person_avatar_url": "http://10.218.8.32:6511/media/documents/2017/04/wang_p.png",
            "organization": "试验室（总承包部）",
            "organizations": None,
            "pagepermission": None,
            "person_signature_url": None,
            "person_telephone": "13340914340",
            "org_code": "ORG30",
            "lat": None,
            "lng": None,
            "last_location_time": None,
            "address": None,
            "gender": "",
            "title": "",
            "relative_signature_url": None,
            "relative_avatar_url": "/media/documents/2017/04/wang_p.png"
        },
        "groups": [
            {
                "id": 17,
                "name": "试验室（总承包部）",
                "permissions": [],
                "pagepermission_set": [
                    "delete0",
                    "delete10",
                    "delete20",
                    "delete30",
                    "panTilt0",
                    "defect0",
                    "reportUE0",
                    "reviewUE0",
                    "reviewQD0",
                    "RISK-A0",
                    "RISK-B0",
                    "RISK-C0",
                    "RISK-D0",
                    "RISK-E0",
                    "RISK-F0",
                    "A1",
                    "B0",
                    "BA1",
                    "BB0",
                    "BBA0",
                    "BBB0",
                    "BBC0",
                    "BC0",
                    "BCA0",
                    "BCB0",
                    "BD0",
                    "C0",
                    "CA0",
                    "CB0",
                    "CC0",
                    "CD0",
                    "CE0",
                    "CF0",
                    "CG0",
                    "D0",
                    "DA0",
                    "DB0",
                    "DC1",
                    "DD1",
                    "DE1",
                    "DF1",
                    "DG1",
                    "DH1",
                    "DI1",
                    "E0",
                    "EH0",
                    "EA0",
                    "EB0",
                    "EC0",
                    "ED0",
                    "EE0",
                    "EF0",
                    "EG0",
                    "EI1",
                    "EK1",
                    "EL0",
                    "EM0",
                    "N0",
                    "NA0",
                    "NB0",
                    "NC0",
                    "ND0",
                    "F0",
                    "FA0",
                    "FB0",
                    "FC0",
                    "FD0",
                    "G0",
                    "GA0",
                    "GB0",
                    "GC0",
                    "H0",
                    "HA0",
                    "HB0",
                    "I1",
                    "IA1",
                    "IB1",
                    "IC1",
                    "ID1",
                    "IE1",
                    "J1",
                    "JD1",
                    "JE1",
                    "JEA1",
                    "JEB1",
                    "JF1",
                    "K0",
                    "KA0",
                    "KAA0",
                    "KAB0",
                    "KB0",
                    "KD0",
                    "KDA0",
                    "KDB0",
                    "KE0",
                    "KF0",
                    "KG0",
                    "L0",
                    "LA0",
                    "LAA0",
                    "LAB0",
                    "LB0",
                    "LBA0",
                    "LBB0",
                    "LBC0",
                    "LBD0",
                    "LBE0",
                    "LBF0",
                    "LBG0",
                    "LBH0",
                    "LBI0",
                    "M0",
                    "MA1",
                    "MB0"
                ],
                "groupcode": None,
                "grouptype": 1,
                "description": "试验室（总承包部）"
            }
        ],
        "is_active": True,
        "is_superuser": False
    },
]
